### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by squidjam** [EMCECS/clarity-react#264]
Hello,
I've noticed development seems to have halted on this project for some time.

Is it still active?

Thanks!

**Comment by akate1** [comment]
@squidjam Yes. It is still active. Are you looking for any specific help or improvement?

**Comment by rbredlau** [comment]
There are recent commits but a released version has not been done in years.  The last issue asking for a released version seems unanswered.

From an outsider's perspective it does not seem active or maintained.

**Comment by squidjam** [comment]
I just had my doubts! I mean, they are justifiable just looking at how this message has been responded after one year.
Cheers.
