### ISSUE TITLE
Unable to use Achieve in project

### ISSUE THREAD

**Issue by andrewanderson58** [EMCECS/clarity-react#82]
Hello,

I have read the other issue that was closed but I am still unable to successfully load this in my project.

I installed the project from a GitHub archive. This actually clones the repo and no transpiled code so I cd'd into the node_modules folder @dell and went through the maker file steps to build the 'dist' file. 

I then imported the `MainContainer` like 
```
import MainContainer from "@dell/clarity-react/dist/layout/main-container/MainContainer";
```

however, I am getting 
```
JSX element type 'MainContainer' does not have any construct or call signatures. 
```

Are you able to provide any more detailed instructions to use this project? Thanks for the work you have done so far I am excited to give it a try.

**Comment by ben-schumacher** [comment]
Hi @andrewanderson58, it appears we did set `default` on the MainContainer export.  Have you tried changing you import like this?
`import {MainContainer} from "@dell/clarity-react/dist/layout/main-container/MainContainer";`

Sorry for the delay in getting back to you.
